AWSTemplateFormatVersion: 2010-09-09
Description: 'A CloudFormation Template to create AWS Secret Attachment.Version:0.1, Description of change: Initial Version'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label: 
        default: Cluster Parameters
      Parameters:
        - InstanceName
        - TargetType
    - Label: 
        default: Secret Parameters
      Parameters:
        - SecretNames
Parameters: 
  InstanceName:
    Type: String
    Description: Enter RDS/Redshift Instance name to attach it with secrets based on SecretType selected.
  TargetType:
    Type: String
    Description: A string that defines the type of service or database associated with the secret (ex). AWS::RDS::DBCluster AWS::Redshift::Cluster.
  SecretNames:
    Type: CommaDelimitedList
    Description: The ARN or name of the secret.
Conditions:
  Secret0Exist: !Not [ !Equals [ !Select [ 0, !Ref SecretNames ], 'NotCreated' ]]
  Secret1Exist: !Not [ !Equals [ !Select [ 1, !Ref SecretNames ], 'NotCreated' ]]
  Secret2Exist: !Not [ !Equals [ !Select [ 2, !Ref SecretNames ], 'NotCreated' ]]
  Secret3Exist: !Not [ !Equals [ !Select [ 3, !Ref SecretNames ], 'NotCreated' ]]
  Secret4Exist: !Not [ !Equals [ !Select [ 4, !Ref SecretNames ], 'NotCreated' ]]
  Secret5Exist: !Not [ !Equals [ !Select [ 5, !Ref SecretNames ], 'NotCreated' ]]
  Secret6Exist: !Not [ !Equals [ !Select [ 6, !Ref SecretNames ], 'NotCreated' ]]
  Secret7Exist: !Not [ !Equals [ !Select [ 7, !Ref SecretNames ], 'NotCreated' ]]
  Secret8Exist: !Not [ !Equals [ !Select [ 8, !Ref SecretNames ], 'NotCreated' ]]
  Secret9Exist: !Not [ !Equals [ !Select [ 9, !Ref SecretNames ], 'NotCreated' ]]
  Secret10Exist: !Not [ !Equals [ !Select [ 10, !Ref SecretNames ], 'NotCreated' ]]
  Secret11Exist: !Not [ !Equals [ !Select [ 11, !Ref SecretNames ], 'NotCreated' ]]
  Secret12Exist: !Not [ !Equals [ !Select [ 12, !Ref SecretNames ], 'NotCreated' ]]
  Secret13Exist: !Not [ !Equals [ !Select [ 13, !Ref SecretNames ], 'NotCreated' ]]
  Secret14Exist: !Not [ !Equals [ !Select [ 14, !Ref SecretNames ], 'NotCreated' ]]
  Secret15Exist: !Not [ !Equals [ !Select [ 15, !Ref SecretNames ], 'NotCreated' ]]
  Secret16Exist: !Not [ !Equals [ !Select [ 16, !Ref SecretNames ], 'NotCreated' ]]
  Secret17Exist: !Not [ !Equals [ !Select [ 17, !Ref SecretNames ], 'NotCreated' ]]
  Secret18Exist: !Not [ !Equals [ !Select [ 18, !Ref SecretNames ], 'NotCreated' ]]
  Secret19Exist: !Not [ !Equals [ !Select [ 19, !Ref SecretNames ], 'NotCreated' ]]
  Secret20Exist: !Not [ !Equals [ !Select [ 20, !Ref SecretNames ], 'NotCreated' ]]
  Secret21Exist: !Not [ !Equals [ !Select [ 21, !Ref SecretNames ], 'NotCreated' ]]
  Secret22Exist: !Not [ !Equals [ !Select [ 22, !Ref SecretNames ], 'NotCreated' ]]
  Secret23Exist: !Not [ !Equals [ !Select [ 23, !Ref SecretNames ], 'NotCreated' ]]
  Secret24Exist: !Not [ !Equals [ !Select [ 24, !Ref SecretNames ], 'NotCreated' ]]
  Secret25Exist: !Not [ !Equals [ !Select [ 25, !Ref SecretNames ], 'NotCreated' ]]
  Secret26Exist: !Not [ !Equals [ !Select [ 26, !Ref SecretNames ], 'NotCreated' ]]
  Secret27Exist: !Not [ !Equals [ !Select [ 27, !Ref SecretNames ], 'NotCreated' ]]
  Secret28Exist: !Not [ !Equals [ !Select [ 28, !Ref SecretNames ], 'NotCreated' ]]
  Secret29Exist: !Not [ !Equals [ !Select [ 29, !Ref SecretNames ], 'NotCreated' ]]
  Secret30Exist: !Not [ !Equals [ !Select [ 30, !Ref SecretNames ], 'NotCreated' ]]
  Secret31Exist: !Not [ !Equals [ !Select [ 31, !Ref SecretNames ], 'NotCreated' ]]
  Secret32Exist: !Not [ !Equals [ !Select [ 32, !Ref SecretNames ], 'NotCreated' ]]
  Secret33Exist: !Not [ !Equals [ !Select [ 33, !Ref SecretNames ], 'NotCreated' ]]
  Secret34Exist: !Not [ !Equals [ !Select [ 34, !Ref SecretNames ], 'NotCreated' ]]
  Secret35Exist: !Not [ !Equals [ !Select [ 35, !Ref SecretNames ], 'NotCreated' ]]
  Secret36Exist: !Not [ !Equals [ !Select [ 36, !Ref SecretNames ], 'NotCreated' ]]
  Secret37Exist: !Not [ !Equals [ !Select [ 37, !Ref SecretNames ], 'NotCreated' ]]
  Secret38Exist: !Not [ !Equals [ !Select [ 38, !Ref SecretNames ], 'NotCreated' ]]
  Secret39Exist: !Not [ !Equals [ !Select [ 39, !Ref SecretNames ], 'NotCreated' ]]
  Secret40Exist: !Not [ !Equals [ !Select [ 40, !Ref SecretNames ], 'NotCreated' ]]
Resources:
  SecretAttachment0:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret0Exist
    Properties:
      SecretId: !Select [ 0, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment1:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret1Exist
    Properties:
      SecretId: !Select [ 1, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment2:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret2Exist
    Properties:
      SecretId: !Select [ 2, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment3:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret3Exist
    Properties:
      SecretId: !Select [ 3, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment4:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret4Exist
    Properties:
      SecretId: !Select [ 4, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment5:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret5Exist
    Properties:
      SecretId: !Select [ 5, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment6:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret6Exist
    Properties:
      SecretId: !Select [ 6, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment7:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret7Exist
    Properties:
      SecretId: !Select [ 7, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment8:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret8Exist
    Properties:
      SecretId: !Select [ 8, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment9:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret9Exist
    Properties:
      SecretId: !Select [ 9, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment10:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret10Exist
    Properties:
      SecretId: !Select [ 10, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment11:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret11Exist
    Properties:
      SecretId: !Select [ 11, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment12:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret12Exist
    Properties:
      SecretId: !Select [ 12, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment13:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret13Exist
    Properties:
      SecretId: !Select [ 13, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment14:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret14Exist
    Properties:
      SecretId: !Select [ 14, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment15:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret15Exist
    Properties:
      SecretId: !Select [ 15, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment16:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret16Exist
    Properties:
      SecretId: !Select [ 16, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment17:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret17Exist
    Properties:
      SecretId: !Select [ 17, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment18:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret18Exist
    Properties:
      SecretId: !Select [ 18, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment19:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret19Exist
    Properties:
      SecretId: !Select [ 19, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment20:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret20Exist
    Properties:
      SecretId: !Select [ 20, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment21:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret21Exist
    Properties:
      SecretId: !Select [ 21, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment22:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret22Exist
    Properties:
      SecretId: !Select [ 22, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment23:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret23Exist
    Properties:
      SecretId: !Select [ 23, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment24:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret24Exist
    Properties:
      SecretId: !Select [ 24, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment25:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret25Exist
    Properties:
      SecretId: !Select [ 25, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment26:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret26Exist
    Properties:
      SecretId: !Select [ 26, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment27:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret27Exist
    Properties:
      SecretId: !Select [ 27, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment28:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret28Exist
    Properties:
      SecretId: !Select [ 28, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment29:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret29Exist
    Properties:
      SecretId: !Select [ 29, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment30:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret30Exist
    Properties:
      SecretId: !Select [ 30, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment31:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret31Exist
    Properties:
      SecretId: !Select [ 31, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment32:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret32Exist
    Properties:
      SecretId: !Select [ 32, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment33:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret33Exist
    Properties:
      SecretId: !Select [ 33, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment34:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret34Exist
    Properties:
      SecretId: !Select [ 34, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment35:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret35Exist
    Properties:
      SecretId: !Select [ 35, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment36:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret36Exist
    Properties:
      SecretId: !Select [ 36, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment37:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret37Exist
    Properties:
      SecretId: !Select [ 37, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment38:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret38Exist
    Properties:
      SecretId: !Select [ 38, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment39:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret39Exist
    Properties:
      SecretId: !Select [ 39, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType
  SecretAttachment40:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Condition: Secret40Exist
    Properties:
      SecretId: !Select [ 40, !Ref SecretNames ]
      TargetId: !Ref InstanceName
      TargetType: !Ref TargetType