AWSTemplateFormatVersion: 2010-09-09
Description: 'This template creates secret manager is to store the GitHub token for the environment (or) account.Version: 0.1, Description of change: Initial Version.'
Parameters:
  EnvironmentType:
    Description: '(Required) Name your EnvironmentType According to your need.'
    Type: String
  ResourceNamePrefix:
    Type: String
    Description: '(Required) Enter prefix for Resource Names'
  GithubToken:
    Type: String
    Description: '(Required) GitHub token value to store in secret manager and which can be used for pipeline creation.'
    NoEcho: true
Resources:
  GithubTokenSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: 'The secret manager is to store the GitHub token for the environment (or) account'
      Name: !Sub '${ResourceNamePrefix}-${EnvironmentType}-GithubToken-Scrt'
      SecretString: !Sub '{ "GithubToken": "${GithubToken}" }'
      Tags:
      - Key: Name
        Value: !Sub '${ResourceNamePrefix}-${EnvironmentType}-GithubToken-Scrt'
      - Key: ApplicationRole
        Value: !Sub 'Github-Scrt'