AWSTemplateFormatVersion: 2010-09-09
Description: 'A CloudFormation Template to create AWS  Secret with dynamic values.Version 0.1'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
    - Label: 
        default: "Naming Conventions"
      Parameters: 
      - ResourceNamePrefix
      - EnvironmentType
      - ServiceName
      - Purpose
      - SecretManagerName
    - Label: 
        default: "Secret Inputs"
      Parameters: 
      - AutoGenerateStringKey
      - SecretString
      - GenerateStringKey
      - PasswordLength
      - SecretPassExcludeCharacters
      - SecretExcludeInputs
Parameters:
  EnvironmentType:
    Type: String
    Description: (Required)Name your EnvironmentType According to your need.
  ResourceNamePrefix:
    Type: String
    Description: (Required)Enter prefix for Resource Names.
  ServiceName:
    Type: String
    Description: (Required)Enter service name for which secret would be used.
  SecretManagerName:
    Type: String
    Description: (Required)Specified value will be used for secret name property.
  Purpose:
    Type: String
    Description: (Required)The value denotes the purpose of the secret in service among other secrets.
  GenerateStringKey:
    Type: String
    Description: (Conditional)Enter key to create auto generate secret(only if AutoGenerateStringKey & SecretString != NULL is true).
  PasswordLength:
    Type: Number
    Description: (Conditional)Enter length of secret for auto generate key(only if AutoGenerateStringKey is true).
  AutoGenerateStringKey:
    Type: String
    Description: (Required)Select true to create auto generate key for secret else false.
    AllowedValues:
      - 'true'
      - 'false'
  SecretString:
    Type: String
    Description: (Required)Enter value for secret string. The value in JSON format (or) string.
    NoEcho: true
  SecretPassExcludeCharacters:
    Type: String
    Description: (Conditional)Enter characters should be excluded from secret string(only if AutoGenerateStringKey is true).
  SecretExcludeInputs:
    Type: CommaDelimitedList
    Description: >-
      (Conditional)Enter the inputs for Generating Secret String in this format
      'ExcludeLowercase,ExcludeNumbers,ExcludePunctuation,ExcludeUppercase,IncludeSpace,RequireEachIncludedType'(only if AutoGenerateStringKey is true).
Conditions:
  ShouldAutoGenerateStringKey: !Equals 
    - true
    - !Ref AutoGenerateStringKey
  IsGenerateStringKey: !Equals 
    - ''
    - !Ref GenerateStringKey
  IsSecretStringEmpty: !Equals 
    - ''
    - !Ref SecretString
Resources:
  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: !Sub 'This is a Secrets Manager secret for ${ServiceName} service.'
      Name: !Ref SecretManagerName
      Tags:
        - Key: Name
          Value: !Ref SecretManagerName
        - Key: ApplicationRole
          Value: !Sub '${ServiceName}-${Purpose}-Scrt'
      SecretString: !If 
        - ShouldAutoGenerateStringKey
        - !Ref 'AWS::NoValue'
        - !Ref SecretString
      GenerateSecretString: !If 
        - ShouldAutoGenerateStringKey
        - SecretStringTemplate: !If 
            - IsSecretStringEmpty
            - !Ref 'AWS::NoValue'
            - !Ref SecretString
          GenerateStringKey: !If 
            - IsGenerateStringKey
            - !Ref 'AWS::NoValue'
            - !Ref GenerateStringKey
          PasswordLength: !Ref PasswordLength
          ExcludeCharacters: !Ref SecretPassExcludeCharacters
          ExcludeLowercase: !Select [ 0, !Ref SecretExcludeInputs]
          ExcludeNumbers: !Select [ 1, !Ref SecretExcludeInputs]
          ExcludePunctuation: !Select [ 2, !Ref SecretExcludeInputs]
          ExcludeUppercase: !Select [ 3, !Ref SecretExcludeInputs]
          IncludeSpace: !Select [ 4, !Ref SecretExcludeInputs]
          RequireEachIncludedType: !Select [ 5, !Ref SecretExcludeInputs]
        - !Ref 'AWS::NoValue'

Outputs:
  SecretName:
    Value: !Ref SecretManagerName
  SecretArn:
    Value: !Ref Secret